---
- name: To implement nmon in to CH3 datacentre
  hosts: 192.168.122.48
  ignore_errors: yes
  tasks:
  - name: To check the file status 
    stat: path=/usr/bin/nmon
    register: folderstatus
  - name: To print Json 
    debug: var=folderstatus
  - name: To install Ubuntu packages from repository (Repository available in CH3 environment)
    apt: name=nmon state=latest
    when: ansible_distribution == "Ubuntu" and folderstatus.changed == "false" 
  - name: To create directory in /root
    file: path=/root/bin state=directory mode=0755 
  - name: The script to the directory 
    copy: src=/tmp/nmond.sh dest=/root/bin/ mode=0655 owner=root group=root
  - name: To create required directory 
    file: path=/var/log/nmon state=directory mode=0755 group=ops mode=775 
  - name: To create file if it dosn't exit if OS distribution  is Ubuntu 
    command: touch /var/spool/cron/crontabs/root 
    when: ansible_distribution == "Ubuntu"
  - name: add the scrip to crontab if OS distribution  is Ubuntu
    lineinfile: path=/var/spool/cron/crontabs/root line="5 0 * * * /root/bin/nmond.sh" regexp='nmond.sh' backup=yes
    when: ansible_distribution == "Ubuntu"
