---
- name: install msi package
  hosts: windows
  tasks:
  - name: Install an MSI, and wait for it to complete before continuing
    win_package:
     path: C:\soft\firefox.exe
     wait: true
     state: present
